apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nodeapp
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodeapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: nodeapp
    spec:
      containers:
        - image: be-test/node-app
          name: node-app
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
