apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: cm9vdC11c2Vy
    mongo-root-password: cm9vdC1wYXNzd29yZA==
    mongo-root-database: YmUtdGVzdA==
    mongo-init: |
        ZGIuY3JlYXRlVXNlcigKICAgICAgICB7CiAgICAgICAgICAgIHVzZXI6ICJiZS10ZXN0LXVzZXIi
        LAogICAgICAgICAgICBwd2Q6ICJiZS10ZXN0LXBhc3N3b3JkIiwKICAgICAgICAgICAgcm9sZXM6
        IFsKICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICByb2xlOiAicmVhZFdyaXRl
        IiwKICAgICAgICAgICAgICAgICAgICBkYjogImJlLXRlc3QiCiAgICAgICAgICAgICAgICB9CiAg
        ICAgICAgICAgIF0KICAgICAgICB9Cik7CgpkYi51c2Vycy5pbnNlcnRPbmUoewoJdXNlcm5hbWU6
        ICdhZG1pbicsCglwYXNzd29yZDogJyQyYiQxMCRNcDIxZHJSLndsQ1h0SjRCZmZUZzEuZEFFYUxy
        Ym5sS0VLa2tQSEV4cGNneExtUVQzeVJHYScsCglyb2xlOiAnYWRtaW4nCn0pOwo=
